get:
  summary: List
  operationId: listProducts
  description: List all products
  tags:
  - products
  parameters:
    - $ref: "../parameters/query/limit.yaml"
  responses:
    '200':
      description: A paged array of products
      headers:
        x-next:
          description: A link to the next page of responses
          schema:
            type: string
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../schemas/Product.yaml"
    default:
      $ref: "../responses/UnexpectedError.yaml"
post:
  summary: Create
  operationId: createProduct
  description: Create a product
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Product.yaml'
  tags:
  - products
  responses:
    '201':
        $ref : "../responses/NullResponse.yaml"
    default:
        $ref : "../responses/UnexpectedError.yaml"

